Repository AliMD/Salav.at, pull requests merged in 2022-03, with the labels that each got.

#78 Feat/upgrade deps
  yarn.lock
Labels: Enhancement

#80 Feat/lint
  .eslintignore
  .eslintrc.yaml
  package.json
  src/config.ts
  src/director.ts
  src/salavat-pwa.ts
  yarn.lock
Labels: Feature

#84 Feat/workflows
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: Enhancement

#87 Release: v1.5.0
  .eslintignore
  .eslintrc.yaml
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/lint.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  index.html
  package.json
  src/config.ts
  src/director.ts
  src/salavat-pwa.ts
  src/stuff/base-element.ts
  src/stuff/chat-room.ts
  src/stuff/data-api.ts
  src/stuff/debounce.ts
  src/stuff/director-assistant.ts
  src/stuff/icon.ts
  src/stuff/page-desktop.ts
  src/stuff/page-home.ts
  src/stuff/salavat-counter.ts
  src/stuff/snack-bar.ts
  src/stuff/style-app-layout.ts
  src/stuff/style-app-responsive.ts
  tsconfig.json
  yarn.lock
Labels: Release Review

#89 Feat/lint
  .eslintrc.yaml
  package.json
  yarn.lock
Labels: Enhancement

#92 Feat/lint
  .eslintrc.yaml
Labels: Enhancement
